baseURL: "/"
languageCode: en-us
title: The Political Science Discipline
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: Slack
      url: "https://poli301.slack.com/"
      weight: 5
params: 
  author: Juan Tellez
  thumbnail: /images/POLI301.png
  instructor: 
    name: Juan Tellez
    email: juan.f.tellez@gmail.com
    url: "https://www.juanftellez.com"
    twitter: juanftellez14
    github: hail2thief
    office: 343 Gambrell Hall
  logo:
    url: /images/POLI301.png
    alt: The Political Science Discipline
  course:
    number: POLI 301
    semester: Fall 2019
    days: "Tuesdays, Thursdays"
    time: "08:30-09:45 AM"
    location: "133 WMBB"
    twitter: juanftellez14
    dates: "August 22–December 06, 2019"
    github: "hail2thief/poli-301"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/juan-f-tellez)
  university: 
    name: University of South Carolina
  school:
    name: Department of Political Science
  primaryColor: "#73000a"
  secondaryColor: "#CC2E40"
  credits: >-
    Course website design adapted/stolen from [Andrew Heiss](https://www.andrewheiss.com/).
  meta:
    twitterSite: "@juanftellez14"
    twitterCreator: "@juanftellez14"
    fbAuthor: ""